/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.forms;

import com.mycompany.proyectofinal.ProyectoFinal;

/**
 *
 * @author mmedina
 */
public class movimientos extends javax.swing.JFrame {

    /**
     * Creates new form movimientos
     */
    public movimientos() {
        ProyectoFinal.setWhereami("movimientos.form");
        System.out.println("movimientos.initComponents-Whereami:"+ProyectoFinal.getWhereami());
        System.out.println("movimientos.initComponents-Whereibeen:"+ProyectoFinal.getWhereibeen());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jBtnCancel3 = new javax.swing.JButton();
        cmbTiprep = new javax.swing.JComboBox<>();
        lblTiprep = new javax.swing.JLabel();
        cmbMnt = new javax.swing.JTextField();
        lblMnt = new javax.swing.JLabel();
        cmbCta = new javax.swing.JComboBox<>();
        lblCta = new javax.swing.JLabel();
        lblDtn = new javax.swing.JLabel();
        txtDtn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(800, 350));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitulo.setText("Movimientos");

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.setEnabled(false);

        jBtnCancel3.setBackground(new java.awt.Color(255, 102, 102));
        jBtnCancel3.setText("Cancelar");
        jBtnCancel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancel3ActionPerformed(evt);
            }
        });

        cmbTiprep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Resumen de Cuentas", "Cuentas por usuario" }));

        lblTiprep.setText("Tipo de reporte:");

        cmbMnt.setText("0.00");
        cmbMnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMntActionPerformed(evt);
            }
        });

        lblMnt.setText("Monto:");

        cmbCta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCtaActionPerformed(evt);
            }
        });

        lblCta.setText("Cuenta:");

        lblDtn.setText("Destino:");

        txtDtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMnt)
                    .addComponent(lblCta)
                    .addComponent(lblDtn)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnCancel3)
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(101, 117, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblTiprep))
                            .addComponent(lblTitulo))
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbTiprep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cmbCta, javax.swing.GroupLayout.Alignment.TRAILING, 0, 99, Short.MAX_VALUE)
                                .addComponent(cmbMnt, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtDtn, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(96, 96, 96))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTiprep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTiprep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMnt)
                    .addComponent(cmbMnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnCancel3)
                    .addComponent(jButton1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(277, 277, 277))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCancel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancel3ActionPerformed
        // TODO add your handling code here:
        System.out.println("click label");
        menu mnu = new menu();
        mnu.show();
        dispose();
    }//GEN-LAST:event_jBtnCancel3ActionPerformed

    private void cmbCtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCtaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCtaActionPerformed

    private void cmbMntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMntActionPerformed

    private void txtDtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:        
        ProyectoFinal.setWhereibeen("movimientos.form");
       // System.out.println("movimientos.windowClosed-Whereami:"+ProyectoFinal.getWhereami());
       // System.out.println("movimientos.windowClosed-Whereibeen:"+ProyectoFinal.getWhereibeen());
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        System.out.println("movimientos.windowOpened:"+ProyectoFinal.getOpcpressed());
        
        switch(ProyectoFinal.getOpcpressed()) {
			case "transfer":
				System.out.println("Opcion Transfer");
                                lblTitulo.setText("Transferencias");
                                
                                lblTiprep.setVisible(false);
                                cmbTiprep.setVisible(false);
                                
                                lblCta.setVisible(true);
                                cmbCta.setVisible(true);
                                
                                lblMnt.setVisible(true);
                                cmbMnt.setVisible(true);
                                
                                lblDtn.setVisible(true);
                                txtDtn.setVisible(true);
                                
                                break;
                                
			case "retiro":
				System.out.println("Opcion Retiro");
                                lblTitulo.setText("Retiro");
                                lblTiprep.setVisible(false);
                                cmbTiprep.setVisible(false);
                                
                                lblCta.setVisible(true);
                                cmbCta.setVisible(true);
                                
                                lblMnt.setVisible(true);
                                cmbMnt.setVisible(true);
                                
                                lblDtn.setVisible(false);
                                txtDtn.setVisible(false);
                                
                                break;
                                
			case "deposito":
				System.out.println("Opcion deposito");
                                lblTitulo.setText("Debito");
                                lblTiprep.setVisible(false);
                                cmbTiprep.setVisible(false);
                                
                                lblCta.setVisible(true);
                                cmbCta.setVisible(true);
                                
                                lblMnt.setVisible(true);
                                cmbMnt.setVisible(true);
                                
                                lblDtn.setVisible(false);
                                txtDtn.setVisible(false);
                                
                                break;
                                
			case "reporte":
				System.out.println("Opcion Reporte");
                                lblTitulo.setText("Reportes");
                                lblTiprep.setVisible(true);
                                cmbTiprep.setVisible(true);
                                
                                lblCta.setVisible(false);
                                cmbCta.setVisible(false);
                                
                                lblMnt.setVisible(false);
                                cmbMnt.setVisible(false);
                                
                                lblDtn.setVisible(false);
                                txtDtn.setVisible(false);
                                
                                break;
                                
		}
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCta;
    private javax.swing.JTextField cmbMnt;
    private javax.swing.JComboBox<String> cmbTiprep;
    private javax.swing.JButton jBtnCancel3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblCta;
    private javax.swing.JLabel lblDtn;
    private javax.swing.JLabel lblMnt;
    private javax.swing.JLabel lblTiprep;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtDtn;
    // End of variables declaration//GEN-END:variables
}
